version: '3.8'

services:
  danboorutools:
    container_name: danboorutools
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    init: true  # protects from chromedriver zombie processes
    command: poetry run watchmedo auto-restart -d /code/danboorutools -p="*" -R -- celery -- -A danboorutools.celery_tasks.tasks worker -B --loglevel=INFO -s /tmp/celerybeat-schedule --autoscale=10,1
    volumes:
      # development
      - ./danboorutools:/code/danboorutools/:ro
      - ./pyproject.toml:/code/pyproject.toml:ro
      - ./poetry.lock:/code/poetry.lock:ro
      - ./sock_config.yaml:/code/sock_config.yaml
      - ./logs:/code/logs/
      - ./data:/code/data/
      - ./tests:/code/tests:ro
      - ./cookies:/code/cookies/
      - ./screenshots:/code/screenshots/
      - ./.ipython:/home/danboorutools/.ipython  # ipython interpreter history persistence
    tmpfs:
      - /tmp

  redis:
    image: redis
    restart: always

  mail:
    image: bytemark/smtp
    restart: always
