services:
  danboorutools:
    container_name: danboorutools
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    init: true  # protects from chromedriver zombie processes
    command: /bin/sh -c "/code/run.sh"
    volumes:
      # development
      - ./danboorutools:/code/danboorutools/:ro
      - ./run.sh:/code/run.sh:ro
      - ./pyproject.toml:/code/pyproject.toml:ro
      - ./poetry.lock:/code/poetry.lock:ro
      - ./sock_config.yaml:/code/sock_config.yaml
      - ./logs:/code/logs/
      - ./data:/code/data/
      - ./tests:/code/tests:ro
      - ./cookies:/code/cookies/
      - ./screenshots:/code/screenshots/
      - ./.ipython:/home/danboorutools/.ipython  # ipython interpreter history persistence
    tmpfs:
      - /tmp

  redis:
    image: redis
    restart: always

  mail:
    image: bytemark/smtp
    restart: always
