[tool.poetry]
name = "danboorutools"
version = "0.0.3"
description = "A set of danbooru admin tools."
authors = ["nonamethanks <nonamethanks@nonamethanks.xyz>"]

[tool.poetry.scripts]
nuke_votes = "danboorutools.scripts.nuke_votes:main"
replace_ehentai_samples = "danboorutools.scripts.replace_ehentai_samples:main"
tag_paid_rewards_on_gelbooru = "danboorutools.scripts.tag_paid_rewards_on_gelbooru:main"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
regex = "^2022.10.31"
python-dateutil = "^2.8.2"
click = "^8.1.3"
loguru = "^0.6.0"
python-dotenv = "^0.21.1"
pydomainextractor = "^0.12.0"
fasttld = "^0.2.1"
selenium = "^4.8.0"
ratelimit = "^2.2.1"
pytz = "^2022.7.1"
filetype = "^1.2.0"
ipython = "^8.9.0"
methodtools = "^0.4.5"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.28.11.8"
pylint = "^2.15.10"
types-python-dateutil = "^2.8.19.6"
ipython = "^8.8.0"
mypy = "^0.991"
autopep8 = "^2.0.1"
types-pkg-resources = "^0.1.3"
flake8 = "^6.0.0"
flake8-annotations = "^3.0.0"
flake8-pyproject = "^1.2.2"
types-pytz = "^2022.7.1.0"

[tool.poetry.group.test.dependencies]
ward = "^0.67.0b0"
ward-coverage = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ward]
path = ["tests"]
hook_module = ["ward_coverage"]

[tool.ward.plugins.coverage]
omit = ["tests/*"]

[tool.autopep8]
max_line_length = 140

[tool.isort]
line_length = 140

[tool.mypy]
ignore_missing_imports = true
no_pretty = true
show_column_numbers = true
show_error_codes = true
check_untyped_defs = true

[tool.flake8]
max-line-length=140
ignore= [
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN101",
    "ANN102",
    "ANN204",
    "W503",
]

[tool.pycodestyle]
max-line-length = 140

[tool.pylint]
disable=[
    "broad-except",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-else-break",
    "no-else-continue",
    "no-else-raise",
    "no-else-return",
    "no-member", # too many stupid false positives: https://github.com/PyCQA/pylint/issues/4693
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-return-statements",
]

[tool.pylint.FORMAT]
max-line-length=140
good-names=[
    "e",
    "id"
]
