socks:
  - name: ban evader
    ban_message: "Sockpuppet of user #123"
    carrier: "My Carrier"
    carrier_organization: "My Carrier Organization"
    ip_prefixes:
      - "123."
      - "124."
    name_patterns:
    - ^pattern1$
    rename_socks: false
    ban_proxies: false # always ban if from proxies
