series:
  - name: "arknights" # tested
    topic_id: 19647
    extra_costume_patterns:
      - r"(?P<base_name>\w+?)_(?P<qualifiers>the_.*)_(?P<series_qualifier>\(arknights\))"

  - name: "azur_lane" # tested
    topic_id: 23519

  - name: "blue_archive" # tested
    topic_id: 21341
    blacklist:
      "kei_(amas)_(blue_archive)": ["kei_(blue_archive)"]

  - name: "fire_emblem" # tested
    topic_id: 22728

  - name: "genshin_impact" # tested
    topic_id: 19285

  - name: "girls'_frontline*"  # not tested, try with the wildcard first
    topic_id: 23293

  - name: "neural_cloud"  # tested
    topic_id: 23293

  - name: "honkai:_star_rail" # tested
    topic_id: 24117

  - name: "kancolle" # tested
    topic_id: 26671
    extra_costume_patterns:
      - r"(?P<base_name>.*?)_(?P<qualifiers>(?:kai_ni|kai)(?:_\(.*\))?)_(?P<series_qualifier>\(kancolle\))"

  - name: "nikke" # tested
    topic_id: 25272

  - name: "pokemon"
    topic_id: 22703

  - name: "princess_connect!"
    topic_id: 25913

  - name: "reverse:1999"
    topic_id: 24504

  - name: "umamusume"
    topic_id: 29925

  - name: "wuthering_waves"
    topic_id: 27205

  - name: xenoblade
    topic_id: 26163
