# how to test regexes:
# * go to https://regex101.com/
# * select "Python" for flavor on the left sidebar
# * insert a costume pattern in the "regular expression" field (without the r"")
# * insert chartags one per line in the "test string" field
# * special qualifiers like arknights_the_costume or kancolle_kai_ni should be captured in the named group extra_qualifier for ease of parsing


# TODO: split qualifier from series name to fix related tags for qualifiers different from series name (kancolle, Codename: Bakery Girl)
series:
  - name: "arknights"
    topic_id: 19647
    wiki_id: 111571
    extra_costume_patterns:
      - r"^(?P<base_name>[^(]+?)(?P<extra_qualifier>the_\w+)(?P<qualifiers>(?:_\(.*\)))*$"

  - name: "azur_lane"
    topic_id: 23519
    wiki_id: 91126

  - name: "blue_archive"
    topic_id: 21341
    wiki_id: 136349
    blacklist:
      - "kei_(amas)_(blue_archive) -> kei_(blue_archive)"

  - name: "cookie_run"
    topic_id: 28362
    wiki_id: 203490

  - name: "fate_(series)"
    autopost: false
    topic_id: 26405
    wiki_id: 218559
    extra_qualifiers:
      - fate

  - name: "fire_emblem"
    topic_id: 22728
    wiki_id: 24408
    extra_qualifiers:
      - fire_emblem_fates
      - fire_emblem_heroes
      - fire_emblem_gaiden
      - fire_emblem_engage
      - fire_emblem_awakening
      - fire_emblem_echoes

  - name: "genshin_impact"
    topic_id: 19285
    wiki_id: 121439
    blacklist:
      - "nadia_(melusine)_(genshin_impact) -> nadia_(genshin_impact)"

  - name: "girls'_frontline"
    topic_id: 23293
    wiki_id: 78438
    extra_qualifiers:
      - girls'_frontline_2
      - neural_cloud
      - reverse_collapse

  - name: "honkai:_star_rail"
    topic_id: 24117
    wiki_id: 148987

  - name: "identity_v"
    topic_id: 32035
    wiki_id: 164998

  - name: "kantai_collection"
    topic_id: 26671
    wiki_id: 62620
    extra_qualifiers:
      - kancolle
    extra_costume_patterns:
      - r"^(?P<base_name>[^(]+?)(?P<extra_qualifier>kai_ni|kai)(?P<qualifiers>(?:_\(.*\)))*$"
    blacklist:
      - "amagi_(battlecruiser)_(kancolle) -> amagi_(kancolle)"

  - name: "goddess_of_victory:_nikke"
    topic_id: 25272
    wiki_id: 186316
    extra_qualifiers:
      - nikke

  - name: "pokemon"
    topic_id: 22703
    wiki_id: 12042
    extra_qualifiers:
      - pokemon_conquest
      - pokemon_go
      - pokemon_heroes
    blacklist:
      - "hex_maniac_(prototype)_(pokemon) -> hex_maniac_(pokemon)"

  - name: "princess_connect!"
    topic_id: 25913
    wiki_id: 188656

  - name: "reverse:1999"
    topic_id: 24504
    wiki_id: 170517

  - name: "umamusume"
    topic_id: 29925
    wiki_id: 126524

  - name: "wuthering_waves"
    topic_id: 27205
    wiki_id: 192114

  - name: "xenoblade"
    topic_id: 26163
    wiki_id: 137054
