# how to test regexes:
# * go to https://regex101.com/
# * select "Python" for flavor on the left sidebar
# * insert a costume pattern in the "regular expression" field (without the r"")
# * insert chartags one per line in the "test string" field
# * special qualifiers like arknights_the_costume or kancolle_kai_ni should be captured in the named group extra_qualifier for ease of parsing

# options:
# topic_id: integer, mandatory
# wiki_ids: array of integers, optional
# extra costume patterns: array of regexes, optional
# extra qualifier: array of strings, optional
# blacklist: array of strings (blacklists specific implication requests)
# group_by_qualifier: boolean, default true, optional (whether single-line BURs are grouped by qualifier)
# allow_sub_implications: boolean, default true (allow costumes to imply other costumes)
# autopost: bool, default true

series:
  - name: "arknights"
    topic_id: 19647
    wiki_ids: [111571]
    extra_costume_patterns:
      - r"^(?P<base_name>[^(]+?)(?P<extra_qualifier>the_\w+)(?P<qualifiers>(?:_\(.*\)))*$"

  - name: "atelier_(series)"
    topic_id: 26873
    wiki_ids: [109224]
    extra_qualifiers:
      - atelier

  - name: "azur_lane"
    topic_id: 23519
    wiki_ids: [91126]

  - name: "blue_archive"
    topic_id: 21341
    wiki_ids: [136349]
    blacklist:
      - "kei_(amas)_(blue_archive) -> kei_(blue_archive)"

  - name: "cookie_run"
    topic_id: 28362
    wiki_ids: [203490]

  - name: "fate_(series)"
    autopost: false
    topic_id: 26405
    wiki_ids: [74111, 139382, 218559]
    extra_qualifiers:
      - fate
      - fate/prototype
      - fate/extra
      - fate/apocrypha
    group_by_qualifier: false

  - name: "fire_emblem"
    topic_id: 22728
    wiki_ids: [24408]
    extra_qualifiers:
      - fire_emblem_fates
      - fire_emblem_heroes
      - fire_emblem_gaiden
      - fire_emblem_engage
      - fire_emblem_awakening
      - fire_emblem_echoes

  - name: "genshin_impact"
    topic_id: 19285
    wiki_ids: [121439]
    blacklist:
      - "nadia_(melusine)_(genshin_impact) -> nadia_(genshin_impact)"

  - name: "girls'_frontline"
    topic_id: 23293
    wiki_ids: [78438]
    extra_qualifiers:
      - girls'_frontline_2
      - neural_cloud
      - reverse_collapse

  - name: honkai_impact_3rd
    topic_id: 25459
    wiki_ids: [181862]
    extra_qualifiers:
      - honkai_impact

  - name: "honkai:_star_rail"
    topic_id: 24117
    wiki_ids: [148987]

  - name: "identity_v"
    topic_id: 32035
    wiki_ids: [164998]

  - name: "kantai_collection"
    topic_id: 26671
    wiki_ids: [62620]
    extra_qualifiers:
      - kancolle
    extra_costume_patterns:
      - r"^(?P<base_name>[^(]+?)(?P<extra_qualifier>kai_ni|kai)(?P<qualifiers>(?:_\(.*\)))*$"
    blacklist:
      - "amagi_(battlecruiser)_(kancolle) -> amagi_(kancolle)"

  - name: "goddess_of_victory:_nikke"
    topic_id: 25272
    wiki_ids: [186316]
    extra_qualifiers:
      - nikke

  - name: "pokemon"
    topic_id: 22703
    wiki_ids: [12042, 29014]
    extra_qualifiers:
      - pokemon_conquest
      - pokemon_go
      - pokemon_heroes
    blacklist:
      - "hex_maniac_(prototype)_(pokemon) -> hex_maniac_(pokemon)"

  - name: "princess_connect!"
    topic_id: 25913
    wiki_ids: [188656]

  - name: "punishing: gray raven"
    topic_id: 25165
    wiki_ids: [171594]
    extra_qualifiers:
      - pgr
    allow_sub_implications: false
    extra_costume_patterns:
      - r"^(?P<base_name>[^(]+?)(?P<extra_qualifier>:\w+)(?P<qualifiers>(?:_\(.*\)))*$"

  - name: "reverse:1999"
    topic_id: 24504
    wiki_ids: [170517]

  - name: "umamusume"
    topic_id: 29925
    wiki_ids: [126524]

  - name: "wuthering_waves"
    topic_id: 27205
    wiki_ids: [192114]

  - name: "xenoblade"
    topic_id: 26163
    wiki_ids: [137054]
